# large or small dataset

dataloader:
  dataset: full      # full | small
  batch_size: 2048    # default 2048

model_settings:
  running_units: 128
  d: 16
  depth: 3
  ffn_mult: 1
  penultimate_units: 512
  alphabet: False
  dropout: 0.1
  prec_type: inject_pre     # embed_input | pretoken | inject_pre | inject_ffn
  inject_pre: False          # inject before Attention block
  inject_post: True         # inject into FFN
  inject_position: last      # all | first | last



train_settings:
  epochs: 1



