# large or small dataset

dataloader:
  dataset: full      # full | small
  batch_size: 2048   # default 2048
  save_path: /cmnfs/proj/prosit_astral/datasets/parquet

model_type: ours
model_settings:
  running_units: 256
  d: 64
  h: 6
  depth: 6
  ffn_mult: 1
  penultimate_units: 512
  alphabet: False
  dropout: 0.1
  integration_method: inject        # embed_input | pretoken | inject | adaptive
  norm_type: layer               # layer | batch | adaptive
  inject_pre: True          # inject before Attention block
  inject_post: False         # inject into FFN
  inject_position: all      # all | first | last | none
  learned_pos: False

prosit:
  model_d: 128 # 64
  embedding_output_dim: 32 # 64
  ff_dim: 256 # 32
  num_heads: 16 # 16
  num_transformers: 6 # 8
  penult_d: 512 # 256
  len_fion: 6 # 6
  dense_dim_factor: 8 # 8
  dropout_rate: 0 # 0
  seq_length: 30 # 30
  transformer_dropout: 0 # 0.1
  
train_settings:
  epochs: 10
  lr_method: static      # static | cyclic | dynamic | decay
  lr_base: 0.0005
  lr_max: 0.001
  log_wandb: True
  lr_dynamic:
    - [1e07, 1e-3, 0, 10_000]
    - [1e-3, 1e-4, 100_000, 140_000]
  seed: 42                             # doesnt quite work yet

wandb_settings:
  log_wandb: True
  name: None
  project: None