# large or small dataset

dataloader:
  dataset: full      # full | small
  batch_size: 2048    # default 2048

model_settings:
  running_units: 128
  d: 16
  depth: 3
  ffn_mult: 1
  penultimate_units: 512
  alphabet: False
  dropout: 0.1
  prec_type: inject        # embed_input | pretoken | inject
  inject_pre: True          # inject before Attention block
  inject_post: False         # inject into FFN
  inject_position: all      # all | first | last | none
  



train_settings:
  epochs: 10
  lr_method: static      # static | cyclic 
  lr_base: 0.0001
  lr_max: 0.001


