

```{r}
library(data.table)
library(ggplot2)
library(introdataviz)
library(egg)
```


```{r}
data <- fread("data.csv")

data$dataset = factor(data$dataset, levels = c("LUM","TOF","AST"))
data$model = factor(data$model, levels = c("full","balanced","single"))

data[, median := round(median(loss), 4), by=.(model, dataset)]
data[, shift_col := ifelse(model=='full', -0.2, 0.2)]

data
```

```{r}
pdf("all.pdf", width = 8, height = 12)

p1 <- ggplot(data[model %in% c("full", "balanced"),], aes(dataset, loss, fill = model, label = median)) +
  geom_split_violin(scale="area") +
  geom_boxplot(width=0.1, outliers = F, coef=0) + 
  ggtitle("Full Dataset Model vs Balanced Dataset Model") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  stat_summary(aes(x = as.numeric(dataset) + shift_col, y=median), fun = "median", geom = "text")



p2 <- ggplot(data[model %in% c("full", "single"),], aes(dataset, loss, fill = model, label = median)) +
  geom_split_violin(scale="area") +
  geom_boxplot(width=0.1, outliers = F, coef=0) +
  ggtitle("Full Dataset Model vs Dataset-Specific Models") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  stat_summary(aes(x = as.numeric(dataset) + shift_col, y=median), fun = "median", geom = "text")

ggarrange(p1,p2, ncol = 1)
dev.off()
```

